site_name: subway-access
site_url: https://subway-access.readthedocs.io/
site_author: "Blaise Albis-Burdige"

repo_name: "random-walks/subway-access"
repo_url: "https://github.com/random-walks/subway-access"
exclude_docs: og-context/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - search.suggest
    - search.highlight
    - navigation.expand
    - navigation.tracking
    - toc.follow
  palette:
    # See options to customise your color scheme here:
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  autorefs: {}
  mkdocstrings:
    handlers:
      python:
        paths: [.]
        inventories:
          - https://docs.python.org/3/objects.inv
        options:
          members_order: source
          separate_signature: true
          filters: ["!^_"]
          show_root_heading: true
          show_if_no_docstring: true
          show_signature_annotations: true
  search: {}

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - CLI Reference: cli.md
  - Architecture: architecture.md
  - Python API: api.md
  - Factor-Factory Integration: factor-factory-integration.md
  - Contributing: contributing.md
  - Releasing: releasing.md
  - Changelog: changelog.md
