name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 9 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Many color libraries just need this variable to be set to any value.
  # Set it to 3 to support 8-bit color graphics (256 colors per channel)
  # for libraries that care about the value set.
  FORCE_COLOR: 3

jobs:
  lint:
    name: Lint and types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@v7

      - name: Install package and dev dependencies
        run: uv sync --group docs --group lint

      - name: Run Ruff
        run: uv run python -m ruff check src tests

      - name: Run mypy
        run: uv run python -m mypy src tests

  checks:
    if: github.event_name != 'schedule'
    name: Tests on Ubuntu Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.12"]

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@v7

      - name: Install package
        run: uv sync

      - name: Test package
        run: >-
          uv run python -m pytest -ra --cov --cov-report=xml --cov-report=term
          --durations=10

      - name: Upload coverage report
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  compatibility:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    name: Compatibility on ${{ matrix.runs-on }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.12", "3.13"]
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - python-version: "pypy-3.11"
            runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - uses: astral-sh/setup-uv@v7

      - name: Install package
        run: uv sync

      - name: Run compatibility tests
        run: uv run python -m pytest -ra

  pass:
    if: always()
    needs: [lint, checks]
    runs-on: ubuntu-slim
    timeout-minutes: 2
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
